name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Debug - Show structure
      run: |
        echo "=== Repository root ==="
        ls -la
        echo "=== MyChatApp directory ==="
        ls -la MyChatApp/
        echo "=== MyChatApp/MyChatApp directory ==="
        ls -la MyChatApp/MyChatApp/

    - name: Build with Maven
      working-directory: MyChatApp/MyChatApp
      run: mvn clean compile test
